# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HoneyBits' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoneyBits
  pod 'Alamofire'
  pod 'PMSuperButton'
  pod 'SwipeCellKit'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'DependencyInjector' 
  pod 'Material'
  pod 'SwiftValidators'
  pod 'IQKeyboardManagerSwift'

  target 'HoneyBitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HoneyBitsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
