Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.100.14"
  config.vm.provision "shell", path: "vagrant_script.sh"

  # config.vm.provider "virtualbox" do |v|
  #   v.name = "HoneyBits Dashboard"
  #   v.cpu = 2
  #   v.memory = 1024
  # end
end
